export const demo1 = [
  { id: "name", label: "Name" },
  { id: "company", label: "Company" },
  { id: "role", label: "Role" },
  { id: "isVerified", label: "Verified" },
  { id: "status", label: "Status" },
  { id: "action", label: "Action" },
];

export const demo2 = [
  { id: "name", label: "Name" },
  { id: "company", label: "Company" },
  { id: "role", label: "Role" },
  // { id: "isVerified", label: "Verified"},
  // { id: "status", label: "Status" },
];

export const tableRow1 = [
  {
    id: "1",
    name: "John Doe",
    company: "Tech Co.",
    role: "Admin",
    isVerified: true,
    status: "Active",
    avatarUrl: "/path/to/avatar1.jpg",
  },
  {
    id: "2",
    name: "Jane Smith",
    company: "Health Inc.",
    role: "User",
    isVerified: false,
    status: "Inactive",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "3",
    name: "John Smith",
    company: "IT Path",
    role: "Developer",
    isVerified: true,
    status: "InActive",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "4",
    name: "Smith Roy",
    company: "Oracle",
    role: "UI/UX",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "5",
    name: "David Warner",
    company: "IBM",
    role: "Developer",
    isVerified: true,
    status: "Active",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "6",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "7",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "8",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "9",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "10",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "11",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "12",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "13",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "14",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "15",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "16",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "17",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "18",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "19",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "20",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "21",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "19",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "22",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "23",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "24",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
  {
    id: "25",
    name: "Tech Smith",
    company: "Infosys",
    role: "QA",
    isVerified: true,
    status: "Banned",
    avatarUrl: "/path/to/avatar2.jpg",
  },
];

export const tableRow2 = [
  {
    id: "1",
    name: "John Doe",
    company: "Tech Co.",
    role: "Admin",
    isVerified: true,
    status: "Active",
    avatarUrl: "/path/to/avatar1.jpg",
  },
  {
    id: "2",
    name: "John Doe",
    company: "Tech Co.",
    role: "Admin",
    isVerified: true,
    status: "Active",
    avatarUrl: "/path/to/avatar1.jpg",
  },
];
